/*INSERT INTO etat_affectationp VALUES(1,'EN_ATTENTE');
INSERT INTO etat_affectationp VALUES(2,'VALIDEE');
INSERT INTO etat_affectationp VALUES(3,'REFUSEE');
INSERT INTO roles(id, name)VALUES (1, 'ROLE_PERSONNEL');
INSERT INTO roles(id, name)VALUES (2, 'ROLE_CHEFSERVCE');	
INSERT INTO roles(id, name)VALUES (3, 'ROLE_DIRECTEUR');	
INSERT INTO roles(id, name)VALUES (4, 'ROLE_RH');
INSERT INTO roles(id, name)VALUES (5, 'ROLE_CORRESPONDANT');

INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (1, '-', '-');
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (2, 'Ariana', 'أريانة');
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (3, 'Béja','باجة');
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (4, 'Ben Arous','بن عروس');
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (5, 'Bizerte', 'بنزرت'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (6, 'Gabès' , 'قابس'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (7, 'Gafsa', 'قفصة'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (8, 'Jendouba', 'جندوبة'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (9, 'Kairouan', 'القيروان'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (10, 'Kasserine', 'القصرين'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (11, 'Kébili', 'قبلي'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (12, 'Le Kef', 'الكاف'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (13, 'Mahdia', 'المهدية'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (14, 'La Manouba', 'منوبة'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (15, 'Médenine', 'المدنين'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (16, 'Monastir', 'المنستير'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (17, 'Nabeul', 'نابل'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (18, 'Sfax', 'صفاقس'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (19, 'Sidi Bouzid', 'سيدي بوزيد'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (20, 'Siliana' , 'سليانة'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (21, 'Sousse', 'سوسة'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (22, 'Tataouine' , 'تطاوين'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (23, 'Tozeur', 'توزر'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (24, 'Tunis', 'تونس'); 
INSERT INTO gouvernorat(id_gouv, nom_gouvfr, nom_gouvar)VALUES (25, 'Zaghouan', 'زغوان');
INSERT INTO public.site (id_site, nature_etablissement_ar, nature_etablissement_fr, nom_etablissement_ar, nom_etablissement_fr, qualite_direction_ar, qualite_direction_fr, id_gouv) VALUES ('1'::bigint, 'Aucune'::character varying, 'Aucune'::character varying, 'Aucune'::character varying, 'Aucune'::character varying, 'Aucune'::character varying, 'Aucune'::character varying, '1'::bigint);
INSERT INTO public.site (id_site, nom_etablissement_fr, nature_etablissement_fr, nom_etablissement_ar, qualite_direction_ar, qualite_direction_fr, nature_etablissement_ar, id_gouv) VALUES ('2'::bigint, 'Centre informatique du ministère de la santé '::character varying, 'EPNA'::character varying, 'مركز الإعلامية لوزارة الصحة'::character varying, 'مدير عام'::character varying, 'directeur général'::character varying, 'منشأة عمومية'::character varying, '24'::bigint);
INSERT INTO public.structure (id_struct, direction, direction_a, division, division_a, service, service_a) VALUES ('1'::bigint, 'Aucune'::character varying, 'Aucune'::character varying, 'Aucune'::character varying, 'Aucune'::character varying, 'Aucune'::character varying, 'Aucune'::character varying);
INSERT INTO public.fonction (id_fonction, nom_fonction, type_fonction) VALUES ('1'::bigint, 'Aucune'::character varying, 'Aucune'::character varying);*/